name: FQL CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Download Flex & Bison
      run: powershell Invoke-WebRequest -Uri "https://github.com/lexxmark/winflexbison/releases/download/v2.5.22/win_flex_bison-2.5.22.zip" -OutFile "tools/flex_bison.zip"
    
    - name: Decompress Flex & Bison
      run: powershell Expand-Archive -Path tools/flex_bison.zip -DestinationPath tools/

    - name: Make
      run: make
